Algoritmo "Calculo salarial"

Var
    salario, novosalario: real

Inicio
      escreva (" valor do seu salario: ")
      leia(salario)
      se (salario > 500)  então
      novosalario := salario + ((salario*10)/100)
      escreval ("seu novo salario é:", novoSalario)
      senão
      novosalario := salario + ((salario*20)/100)
      escreval ("seu novo salario é:", novoSalario)

      fimse

Fimalgoritmo


